---
galaxy_info:
  role_name: grafana
  author: community
  description: Configure Grafana organizations, dashboards, folders, datasources, silences, teams and users
  license: GPLv3
  min_ansible_version: "2.15"
  galaxy_tags: [grafana, monitoring]
  platforms:
    - {name: EL, versions: [all]}
    - {name: Fedora, versions: [all]}
    - {name: Amazon, versions: [all]}
    - {name: Debian, versions: [all]}
    - {name: Ubuntu, versions: [all]}
